### ISSUE TITLE
[BUG] Referer Checking added for hentaistream.moe

### ISSUE THREAD

**Issue by nekomimiiii** [gan-of-culture/get-sauce#60]
**Describe the bug**
Referer checking added on our Servers

**To Reproduce**
1. Referer for HTTP request to the CDN-server must be set at least to "https://hentaistream.moe/"
2. otherwise you will see an 403.

**Additional context**
Hello, I am one of the Admins of Hentaistream, and wanted to inform you, that we enforce HTTP-Referer-Checking because our Service is being used by other Websites as CDN.

Hopefully you can implement the fix quite easily.

Have a great new year 2022! ;)

**Comment by gan-of-culture** [comment]
Hi,

I was thinking this might be the issue since I was refactoring my unit tests and saw that there was this issue not only in this web-scraper, but also on your website. I am glad to see that you were able to fix it so quickly and even more so I am happy that you even took your time to make a issue here ;D

I am very much a fan of https://hentaistream.moe/ and the godlike content you guys provide! This is a awesome start to 2022 and I hope you guys also have a great 2022!

Stay healthy!

**Comment by nekomimiiii** [comment]
Yeah, also we are fixing something on our Services. Some tests may fail the test, because we "Destroy" our Kube-Containers at the Moment xD

**Comment by gan-of-culture** [comment]
btw do you guys use a self trained model of ESRGAN or a public pre-trained model like: RealESRGAN_x4plus_anime_6B.pth? Since it says on your patreon that you guys have a lot of energy costs caused by the upscaling of videos.

I recently used this project with enables me to upscale at x4 resolution with a speed of ~14fps using one 3080. Check it out if you're interested: [https://github.com/styler00dollar/vs-RealEsrganAnime-tensorrt-docker](https://github.com/styler00dollar/vs-RealEsrganAnime-tensorrt-docker)
