### ISSUE TITLE
Question about Separated Caption and Timeout 

### ISSUE THREAD

**Issue by zajimumaaa** [gan-of-culture/get-sauce#65]
## Separated Caption
- Is there any reason why it's always merged into .mp4 container/file format instead of original container?
- Is there any option to not merge them ? so they are still separated video & subs. If yes how to do it ? if no could you add option for that? or seperated video and subs is not "best practice" kind of thing so you merge them?

## Timeout
- I'm using pi-hole + unbound, so the first request would take long time and I often have `TLS handshake timeout`, is it possible to increase the timeout?

**Comment by gan-of-culture** [comment]
1. It's merged in to .mp4 most of the time since that is the go to format most sites use. Some sites use .webm and that as far as I know doesn't support subtitles. Because it doesn't .webm files will be also merged into .mp4. If the original file format from the website is .mkv for example, then the merged result should also be .mkv.
2. if you are using the newest version (v1.2.6) the option to do that is -k. (see the options part on the readme)

3. Sounds like a good idea. I will add that for the next release.

**Comment by gan-of-culture** [comment]
Actually can you provide further information about the TLS handshake timeout issue? The default timeout is set to 10 seconds. It's quite hard to believe that you need more than 10 seconds for a TLS handshake.

Please provide the following:
- What OS are you on?
- The URL you are trying to extract
- If possible like a screenshot of the program output

**Comment by zajimumaaa** [comment]
> It's quite hard to believe that you need more than 10 seconds for a TLS handshak

Hmm maybe it's just my ISP then, sorry to bother you.

**Comment by gan-of-culture** [comment]
You can test it if increasing the timeout actually helps your issue, by increasing the timeout time here. [https://github.com/gan-of-culture/get-sauce/blob/b1c3bf3c6c5b9b7cfb835b1b959da9da5ee5331d/request/request.go#L52](https://github.com/gan-of-culture/get-sauce/blob/b1c3bf3c6c5b9b7cfb835b1b959da9da5ee5331d/request/request.go#L52)

For that you need to download the source code and the latest version of Golang. Then use the ```go run main.go ...``` command to run the program. For more info checkout the readme.md :)

**Comment by gan-of-culture** [comment]
If you find out further information, let me know. For now I will close this issue.
